:pidfile: tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log

tasks: &tasks
  update_info_job:
    every: '25m' # cron: '10 0 * * * *'
    class: UpdateInfoJob
    queue: default
    description: "This job update the informacion about the covid for all countries"
  wake_up_job:
    every: '12m' # cron: '10 0 * * * *'
    class: WakeUpJob
    queue: default
    description: "This job wake up to himself"
:schedule:
  <<: *tasks